### ISSUE TITLE
Can I stop deleting messages from other bots?

### ISSUE THREAD

**Issue by VoltIcaRus** [KOZ39/DEEB#1]
Hello, sorry for my rookie question.
I am not a professional programmer
this code works fine
There is a problem with deleting messages from other bots
I tried several things to solve this but I'm not sure
Can I ignore specific roles or other bots?

**Comment by KOZ39** [comment]
I'll give you an example code, so use whatever you want.
> P.S. This code has only been tested on discord.py 2.1.0

```
# Ignore specific roles
role = discord.utils.get(message.guild.roles, name="G")
if role not in message.author.roles:
    await message.delete()
await message.channel.send(embed=embed, reference=message.reference, mention_author=False)
```
```
# Ignore all bots
if not message.author.bot:
    await message.delete()
await message.channel.send(embed=embed, reference=message.reference, mention_author=False)
```
```
# Ignore specific id
exc = (194732546674655232,)
if message.author.id not in exc:
    await message.delete()
await message.channel.send(embed=embed, reference=message.reference, mention_author=False)
```

**Comment by VoltIcaRus** [comment]
The answer was helpful. It was a problem with discord.py 1.7.3
Upgraded to 2.1 and it was resolved.
happy new year.

**Comment by KOZ39** [comment]
Happy New Year!
